spring.application.name=GenomaBankAPI

# Puerto del servidor
server.port=8080

# Ruta base para los endpoints (opcional, puedes dejarla si quieres mantener /genomabanck)
server.servlet.context-path=/genomebanck

# Configuración de la conexión con MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/genomebanck?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=morita2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# (Opcional) Nivel de logging para ver las consultas más claras en consola
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE