
spring.application.name=GenomaBankAPI
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/genomabanck
spring.datasource.username=root
spring.datasource.password=orscon
server.servlet.context-path=/genomabanck
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ======================================================================
# CONFIGURACIÓN MANUAL:
#
# "validate" -> No crea ni modifica nada. Solo comprueba al arrancar que
#               las tablas de la BD coincidan con tus @Entity. Si no,
#               la aplicación fallará (lo cual es bueno, te avisa de un error).
spring.jpa.hibernate.ddl-auto=update
#
# "never" -> Le decimos a Spring que NUNCA ejecute ningún script
#            (ni data.sql ni import.sql). Nosotros nos encargamos.
spring.sql.init.mode=never
# ======================================================================

jwt.secret=bXN1cGVyc2VjcmV0Zm9yZ2Vub21hYmFua2FwaWlzc3VwZXJsb25nYW5kc2VjdXJl
jwt.exp-min=60